Show_message_bubbles:
  type: bool
  default: true
  description: 'Show messages in speech bubbles'

Your_message_bubble_color:
  type: enum
  default: green
  choices:
    - primary
    - secondary
    - tertiary
    - black
    - white
    - gray
    - silver
    - maroon
    - red
    - purple
    - fushsia
    - green
    - lime
    - olive
    - yellow
    - navy
    - blue
    - teal
    - aqua
  description: 'Select the background color of <b>your</b> messages, sent from you.<br>The primary, secondary and teriary options are taken from your theme color settings.'

Other_message_bubble_color:
  type: enum
  default: blue
  choices:
    - primary
    - secondary
    - tertiary
    - red
    - orange
    - yellow
    - green
    - blue
    - purple
  description: 'Select the background color of <b>other</b> messages, sent to you.<br>The primary, secondary and teriary options are taken from your theme color settings.'

Message_bubble_opacity:
  type: enum
  default: 10%
  choices:
    - 5%
    - 10%
    - 15%
    - 20%
    - 25%
  description: 'Select the opacity of the background colors. The larger the percentage the deeper more color'
  
Show_box_shadow:
  type: bool
  default: true
  description: 'Show a box shadow on the message bubbles' 
  
Message_button_added_text:
  type: string
  default: ''
  description: 'Text to be appended to "Reply" button'

