show_message_bubble:
  type: bool
  default: true
  description: 'Show messages in speech bubbles'

message_bubble_color:
  type: enum
  default: link
  choices:
    - primary
    - link
    - red
    - orange
    - yellow
    - green
    - blue
    - purple
  description: 'Select background color of the message bubbles. The primary and link options are taken from your site settings.'
  
  message_bubble_opacity:
  type: enum
  default: 10%
  choices:
    - 5%
    - 10%
    - 15%
    - 20%
    - 25%
  description: 'Select opacity of the background color. The larger the percentage the deeper more color'
  
message_button_added_text:
  type: string
  default: ''
  description: 'Text to be appended to "Reply" button'

